module.exports = {
  id: 'VAGUE_TERMS',
  label: 'Vague Terms',
  severity: 'Medium',
  weight: 2,
  explanation: 'Vague terms introduce subjective interpretation and lack measurable acceptance criteria.',
  suggestion: 'Replace vague terms with measurable target values or specific quantitative criteria (e.g. "respond within 2 seconds").',
  words: [
    'fast',
    'quick',
    'slow',
    'easy',
    'user-friendly',
    'simple',
    'flexible',
    'robust',
    'efficient',
    'appropriate',
    'adequate',
    'reasonable',
    'sufficient',
    'normal',
    'good',
    'better',
    'best',
    'modern',
    'minimal',
    'maximal',
    'seamless',
    'intuitive',
  ],
};
